# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  sha: 1.11.0
  hooks:
    - id: shellcheck
